title: Gabe's Minecraft Server
description: Server Information and Changelog for Gabe's Minecraft Server

<link rel="shortcut icon" type="image/png" href="{{ "/assets/images/favicon.png"  | absolute_url }}">
